### ISSUE TITLE
The URL of "Jump to Ranking Website" on the title screen is old

### ISSUE THREAD

**Issue by rinki-sorami** [TeruMiyake/Typing-is-Nonsense#1]
The URL of "Jump to Ranking Website" on the title screen is old. It should refer to "https://tin.terum.jp/", not to "https://terum.jp/tin/".

Assets/Scripts/Title/TitleManager.cs
...
    void JumpToWebsite()
    {
        Application.OpenURL("https://terum.jp/tin/");
    }

**Comment by TeruMiyake** [comment]
**Resolved:** Thank you, rinki-sorami san!
